name: Documentation deployment

on: [ push ]

jobs:
  deploy:
    if: startsWith(github.repository, 'nbbrd/') && ((github.ref == 'refs/heads/develop') || startsWith(github.ref, 'refs/tags/v'))
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    env:
      THEME_VERSION: v0.32.3
      DOC_SLUG: ${{ github.ref_name }}
      DOC_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/${{ github.ref_name }}"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Download theme
        run: |
          mkdir -p docs/themes/hugo-geekdoc/
          curl -sSL https://github.com/thegeeklab/hugo-geekdoc/releases/download/${{ env.THEME_VERSION }}/hugo-geekdoc.tar.gz | tar -xz -C docs/themes/hugo-geekdoc/ --strip-components=1

      - name: Build pages
        run: |
          hugo --source docs -b ${{ env.DOC_URL }}
          touch ./docs/public/.nojekyll

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          destination_dir: ./docs/${{ env.DOC_SLUG }}

      - name: Create summary
        run: echo "Documentation available at ${{ env.DOC_URL }}" >> $GITHUB_STEP_SUMMARY
